version: "3"
services:
  client:
    image: docker.pkg.github.com/alcinae/essentiel/client:beta-compose
    ports:
      - "4200:4200"
    # volumes:
    #   - "./client:/app"
    # networks:
    #   - "api"
    restart:
      always

  server:
    image: docker.pkg.github.com/alcinae/essentiel/server:beta-compose
    ports:
      - 8080:8080
    networks:
      # - "api"
      - "database"
    restart:
      always

#  mysql:
#    build:
#        context: db
#        dockerfile: dockerfile
#    networks: 
#        - "database"
#    env_file:
#        - ./docker.env #TODO: Change credentials
#    environment:
#        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#        MYSQL_DATABASE: "db"
#    volumes:
#        - "db"
#    restart: 
#        always
    
  # wiki:
  #   build:
  #     context: wiki
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   restart:
  #     always

networks:
  api:
  database:

volumes:
  db:
