version: "3"
services:
  client:
    image: docker.pkg.github.com/alcinae/essentiel/client:beta-compose
    networks:
      - "proxy"
    restart:
      always

  server:
    image: docker.pkg.github.com/alcinae/essentiel/server:beta-compose
    networks:
      - "proxy"
      - "database"
    restart:
      always

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - "proxy"
    ports:
      - 80:80
      - 443:443
    environment:
      - ENV=development
      # - CLIENT=http://client:4200
      # - SERVER=http://server:8080
      # - WIKI=http://wiki:8000
    depends_on:
      - client
      - server
      # - wiki

#  database:
#    build:
#        context: db
#        dockerfile: dockerfile
#    networks: 
#        - "database"
#    env_file:
#        - ./docker.env #TODO: Change credentials
#    environment:
#        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#        MYSQL_DATABASE: "essentiel"
#    volumes:
#        - "db"
#    restart: 
#        always
    
  # wiki:
  #   build:
  #     context: wiki
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   restart:
  #     always

networks:
  proxy:
  database:

volumes:
  db: