version: "3"
services:
  client:
    image: docker.pkg.github.com/alcinae/essentiel/client:beta
    ports:
      - "80:4200"
    # volumes:
    #   - "./client:/app"
    networks:
      - "api"
    restart:
      always

  server:
    image: docker.pkg.github.com/alcinae/essentiel/server:beta 
    networks:
      - "api"
      - "database"
    restart:
      always

  mysql:
    build:
        context: db
        dockerfile: dockerfile
    networks: 
        - "database"
    env_file:
        - ./docker.env #TODO: Change credentials
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: "db"
    volumes:
        - "db"
    restart: 
        always
    
  # doc:
  #   build: dockerfile_docs
  #   ports:
      
  #   restart:
  #     always

networks:
  api:
  database:

volume:
  db: