version: "3"
services:
  client:
    build: ./client
    ports:
      - "80:4200"
    # volumes:
    #   - "./client:/app"
    links:
      - "server"
    restart:
      always

  server:
    image: docker.pkg.github.com/alcinae/essentiel/server 
    links:
      - "client"
    restart:
      always

  mysql:
    networks: 
        - "database"
    build:
        context: db
        dockerfile: dockerfile
    env_file:
        - ./docker.env #TODO: Change credentials
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: "db"
    volumes:
        - "db"
    restart: 
        always
    
  doc:
    build: dockerfile_docs
    ports:
      
    restart:
      always

networks:
  database:

volume:
  db: