package fr.startintech.essentiel.controller;

import fr.startintech.essentiel.data.model.Structure;
import fr.startintech.essentiel.data.repository.StructureRepository;
import fr.startintech.essentiel.exeption.IdMismatchException;
import fr.startintech.essentiel.exeption.NotFoundException;
import org.apache.tomcat.util.http.fileupload.FileUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/**
 * Structure REST Controller
 */
@RestController // This means that this class is a Controller
@CrossOrigin(origins = "*", maxAge = 3600)
@RequestMapping(path="/api/structure") // This means URL's start with /api (after Application path)
public class StructureController {
    @Autowired  // This means to get the bean called StructureRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StructureRepository repository;

    /**
     * Get all structures
     * @return a list of Structures
     */
    @GetMapping // Map ONLY GET Requests
    public List<Structure> findAll() {
        // This returns a JSON or XML with the structures
        return repository.findAll();
    }

    /**
     * Get structure by name
     * @param structureName structure's name
     * @return called structure
     */
    @GetMapping("/name/{structureName}") // Map ONLY GET Requests
    public Structure findByName(@PathVariable String structureName) {
        // @PathVariable means it is a parameter from path
        return repository.findByName(structureName);
    }

    /**
     * Get Structure by id
     * @param id structure's id
     * @return called structure
     * @throws NotFoundException
     */
    @GetMapping("/{id}") // Map ONLY GET Requests
    public Structure findById(@PathVariable Long id) throws NotFoundException {
        return repository.findById(id)
                .orElseThrow(NotFoundException::new);
    }

    /**
     * Create a new structure
     * @param structure structure to create
     * @return created structure
     */
    @PostMapping // Map ONLY POST Requests
    @PreAuthorize("hasRole('USER') or hasRole('PM') or hasRole('ADMIN')")
    @ResponseStatus(HttpStatus.CREATED)
    public Structure create(@RequestBody Structure structure) {
        if (structure.getName() != null && !structure.getName().isBlank()) {
            try {
                FileWriter myWriter = new FileWriter("docs/structures/" + structure.getName().toLowerCase() + ".md");

                maskWiki(myWriter, structure);

                myWriter.close();
                System.out.println("Successfully wrote to the file.");
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        }
        return repository.save(structure);
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('USER') or hasRole('PM') or hasRole('ADMIN')")
    public void delete(@PathVariable Long id) throws NotFoundException {
        if (repository.findById(id).isPresent()) {
            File fileToDelete = new File("docs/structures/" + repository.findById(id).get().getName().toLowerCase() + ".md");
            if (fileToDelete.delete()) {
                System.out.println("Deleting the file: " + fileToDelete.getName().toLowerCase());
            } else {
                System.out.println("Failed to delete the file : " + fileToDelete.getName());
            }
            repository.deleteById(id);
        } else throw new NotFoundException();
    }

    /**
     * Delete all structures
     */
    @DeleteMapping // Map ONLY DELETE Requests
    @PreAuthorize("hasRole('ADMIN')")
    public void deleteAll() throws IOException {
        FileUtils.cleanDirectory(new File("docs/structures/"));
        System.out.println("Deleting all structure files");
        repository.deleteAll();
    }

    /**
     * Update sent structure
     * @param structure structure to update
     * @param id Structure id
     * @return saved structure
     * @throws IdMismatchException
     * @throws NotFoundException
     */
    @PutMapping("/{id}") // Map ONLY PUT Requests
    @PreAuthorize("hasRole('USER') or hasRole('PM') or hasRole('ADMIN')")
    public Structure updateStructure(@RequestBody Structure structure, @PathVariable Long id) throws IdMismatchException, NotFoundException {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        repository.findById(id).orElseThrow(NotFoundException::new);
        structure.setId(id);
        structure.setUpdatedAt(new Date());
        if (structure.getName() != null && !structure.getName().isBlank()) {
            try {
                FileWriter myWriter = new FileWriter("docs/structures/" + structure.getName().toLowerCase() + ".md");

                maskWiki(myWriter, structure);

                myWriter.close();
                System.out.println("Successfully wrote to the file.");
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        }

        return repository.save(structure);
    }

    private void maskWiki(FileWriter myWriter, Structure structure) throws IOException {
        String createdTime = new SimpleDateFormat("EEEE dd MMM yyyy 'à' HH:mm:ss", Locale.FRANCE).format(structure.getCreatedAt());
        myWriter.write("## Présentation de la structure\n");
        myWriter.write("- Nom : " + structure.getName() + "\n");
        if (structure.getName() != null) {
            myWriter.write("- Nom : " + structure.getName() + "\n");
        }
        if (structure.getType() != null) {
            myWriter.write("- Type : " + structure.getType() + "\n");
        }
        if (structure.getAddress() != null) {
            myWriter.write("- Adresse : " + structure.getAddress() + "\n");
        }
        if (structure.getLabel() != null) {
            myWriter.write("- Label : " + structure.getLabel() + "\n");
        }
        myWriter.write("\n");
        if (structure.getDescription() != null) {
            myWriter.write("## Description : \n" + structure.getDescription() + "\n");
        }
        myWriter.write("\n");
        if (structure.getContactName() != null || structure.getPhone() != null || structure.getEmail() != null) {
            myWriter.write("## Contact : \n");
            myWriter.write("\n");
            if (structure.getContactName() != null && structure.getContactFunction() != null) {
                myWriter.write("- Nom : " + structure.getContactName() + " (" + structure.getContactFunction() + ") \n");
            }
            if (structure.getPhone() != null) {
                myWriter.write("- N° de téléphone : " + structure.getPhone() + "\n");
            }
            if (structure.getEmail() != null) {
                myWriter.write("- Email : " + structure.getEmail() + "\n");
            }
        }
        myWriter.write("\n");
        myWriter.write("\n");
        myWriter.write("*Ajoutée le : " + createdTime + "*\n");
        if (structure.getUpdatedAt() != null) {
            String updatedTime = new SimpleDateFormat("EEEE dd MMM yyyy 'à' HH:mm:ss", Locale.FRANCE).format(structure.getUpdatedAt());
            myWriter.write("*Dernière mise à jour le : " + updatedTime + "*\n");
            myWriter.write("\n");
        }
    }
}
